---
title: "Lab 02 - Take a sad plot and make it better"
author: "Group Members: Finley, Sam, Claire and user4"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
```

```{r load-data, message = FALSE}
staff <- read_csv("data/instructional-staff.csv")
```


--------

### Exercise 1

5x11 so 55 rows

--------

Team member 2 should pull to download updates and begins here.

### Exercise 2

```{r staff-long-create}

staff_long <- staff %>%
  pivot_longer(
    cols = -faculty_type,     
    names_to = "Year",
    values_to = "Percentage_of_highers"
    )
```


### Exercise 3

Yes it looks right.

```{r staff-long-inspect}

```



--------


### Exercise 4



```{r lineplot-1}
staff_long %>%
  ggplot(aes(x = Year, y = Percentage_of_highers, color = faculty_type)) +
  geom_point()
```


### Exercise 5

Part time faculty greatly increased

--------

### Exercise 6

*Remove this text and add your answer here.*

```{r lineplot-3}
# remove this comment and add your code here
```


Current team member should knit, stage & commit, and push all changes to GitHub.

--------

Next team member should pull to download updates and continue from here.


### Exercise 7

*Remove this text and add your answer here. No code needed for this exercise!*


### Exercise 8

*Remove this text and add your answer here.*

```{r lineplot-4}
# remove this comment and add your code here
```


Current team member should knit, stage & commit, and push all changes to GitHub.

--------

All team members should pull to download all updates.


